package com.huawei.it.roma.liveeda.policycenter.domain;

public enum DecisionReason {
    NO_AUTH_REQUIRED,
    CONVERSATION_AUTHORIZED,
    USER_AUTHORIZATION_REQUIRED,
    TOOL_NOT_BOUND,
    USER_TOOL_ACCESS_DENIED,
    INVALID_TOKEN_ID,
    POLICY_STORE_UNAVAILABLE,
    AUTHORIZATION_STORE_UNAVAILABLE
}
